### ISSUE TITLE
Install - Do not start php session before send header

### ISSUE THREAD

**Issue by RobinTheHood** [jtl-software/connector-modified#2]
In `/install/index.php` is a lot of html output before the session is started in line 61 by calling the constructor of `\jtl\Connector\Modified\Installer\Installer()`. This results in a warning and on a non-working session. Maybe the session should be started earlier or the installer has to work without session.

Link to your forum:
https://forum.jtl-software.de/threads/kein-abspeichern-der-konfigurtion-moeglich.139833/#post-780161

**Comment by drieschel** [comment]
Thank you for reporting @RobinTheHood. This should be solved with v3.2.0.

**Comment by RobinTheHood** [comment]
Thx!
